import { AppShell } from "@/components/layout/app-shell";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { integrations, pendingOrders } from "@/lib/sample-data";

export default function IntegrationsPage() {
  return <AppShell><div className="mb-5"><h1 className="text-2xl font-semibold tracking-normal">Orders / Integrations</h1><p className="mt-1 text-sm text-muted-foreground">Customer order software, cameras, Supabase, finance exports, and imported request notes.</p></div><div className="grid gap-4 xl:grid-cols-[1fr_420px]"><Card><CardHeader><CardTitle>Integration endpoints</CardTitle><CardDescription>Systems connected to the weighbridge workflow.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Direction</TableHead><TableHead>Endpoint</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{integrations.map((item) => <TableRow key={item.name}><TableCell>{item.name}</TableCell><TableCell>{item.direction}</TableCell><TableCell className="font-mono text-xs">{item.endpoint}</TableCell><TableCell><Badge variant="outline">{item.status}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardHeader><CardTitle>Recent imported notes</CardTitle><CardDescription>Data arriving from the business systems.</CardDescription></CardHeader><CardContent className="grid gap-3">{pendingOrders.map((order) => <div className="rounded-md border p-3" key={order.externalNoteId}><div className="font-mono text-xs text-muted-foreground">{order.externalNoteId}</div><div className="mt-1 font-medium">{order.product}</div><div className="text-sm text-muted-foreground">{order.businessUnit} / {order.vehiclePlate}</div></div>)}</CardContent></Card></div></AppShell>;
}
